\i Person.sql
\i Standort.sql
\i Mannschaft.sql
\i Mitglied.sql
\i Angestellter.sql
\i Trainer.sql
\i Spieler.sql
\i FanClub.sql
\i Betreut.sql
\i Spiel.sql
\i Spielt.sql
\i SpielerEigenschaft.sql
\i TrainerEigenschaft.sql
